name: 'Create Unity Homebrew Casks'

on:
  workflow_dispatch:
    inputs:
      unityversion:
        description: 'Unity version to build casks for (2020.3.18f1 for example).'
        required: true

env:

jobs:
  buildfilematrix:
    runs-on: ubuntu-latest
    outputs:
      filematrix: ${{ steps.set-matrix.outputs.filematrix }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Matrix
        id: set-matrix
        run: |
          echo "::set-output name=filematrix::$(ls templates/casks/ | \
                jq --raw-input | \
                jq --slurp --compact-output)"


  generatecasks:
    needs: buildfilematrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        templatefile: "${{ fromJson(needs.buildfilematrix.outputs.filematrix }}"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Execute createcasks.sh
        run: |
          ./.github/workflows/scripts/createcasks.sh -v '${{ github.event.inputs.unityversion }}' -t '${{ matrix.templatefile }}'
          cat Casks/'${{ matrix.templatefile }}''${{ github.event.inputs.unityversion }}'
