name: 'Create Unity Homebrew Casks'

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      unityversion:
        description: 'Unity version to build casks for (2020.3.18f1 for example).'
        required: true

jobs:
  buildfilematrix:
    runs-on: ubuntu-latest
    outputs:
      filematrix: ${{ steps.set-matrix.outputs.filematrix }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Matrix
        id: set-matrix
        run: |
          echo "::set-output name=filematrix::$(ls templates/casks/ | jq --raw-input | jq --slurp --compact-output)"


  generatecasks:
    needs: buildfilematrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        templatefile: "${{ fromJson(needs.buildfilematrix.outputs.filematrix) }}"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Dependencies
        run: |
          brew install jinja2-cli

      - name: Execute createcasks.sh
        run: |
          ./.github/workflows/scripts/createcasks.sh -v '${{ github.event.inputs.unityversion }}' -t '${{ matrix.templatefile }}'

      - uses: actions/upload-artifact@v2
        with:
          name: NewCasks
          path: |
            newcasks/*


  generatepr:
    needs: generatecasks
    runs-on: ubuntu-latest

    steps:
      - name: Download NewCasks
        uses: actions/download-artifact@v2
        with:
          name: NewCasks
          path: newcasks/

      - name: Authenticate gh Tool
        run: |
          # Auth the gh tool using the token provided for each workflow run.
          echo "$TOKEN" | gh auth login --with-token > /dev/null 2>&1

      - name: Create PR For New Casks
        run: |
          git checkout -b newcasks
          git add newcasks/*
          git commit -am 'New casks generated for Unity ${{ github.event.inputs.unityversion }}'
          git push --set-upstream origin newcasks

          gh pr create --fill
